Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,9 +25,20 @@ jobs:
       run: npm install
 
     - name: Start server
-      run: npm start
-      # Attendre que le serveur soit prêt
-      # Peut-être utiliser un script personnalisé pour vérifier si le serveur est prêt
+      run: |
+        npm start &
+        until $(curl --output /dev/null --silent --head --fail http://localhost:3000); do
+            echo "Waiting for server to start..."
+            sleep 1
+        done
+        echo "Server started successfully."
 
     - name: Run end-to-end tests with Cypress
-      run: npm run cy:run
+      run: |
+        npm run cy:run
+        if [ $? -eq 0 ]; then
+          echo "All tests passed successfully."
+        else
+          echo "Some tests failed. Check the logs for details."
+          exit 1
+        fi
